// One consistent icon set (react-bootstrap-icons) — no emoji. Lives apart
// from the sidebar so the tile grid shows the same glyph per section without
// a second copy of the map.
import {
    ArrowLeftRight,
    CheckCircle,
    ClockHistory,
    CloudDownload,
    Collection,
    Controller,
    ExclamationTriangle,
    Flag,
    Grid3x3,
    type Icon as IconType,
    Layers,
    ListCheck,
    ListOl,
    ListUl,
    Palette,
    PatchCheck,
    PersonCheck,
    PersonX,
    ShieldLock,
    Sliders,
    Speedometer2,
    Trophy,
} from 'react-bootstrap-icons';
import type { NavItemId } from '~app/(new-layout)/games/[game]/manage/console/nav-model';

export const NAV_ICON: Record<NavItemId, IconType> = {
    overview: Speedometer2,
    'mod-queue': CheckCircle,
    'queue-history': ClockHistory,
    'auto-verify': PatchCheck,
    attention: ExclamationTriangle,
    roster: ListOl,
    reports: Flag,
    bans: PersonX,
    history: ClockHistory,
    setup: ListCheck,
    'game-details': Controller,
    theme: Palette,
    'categories/list': ListUl,
    'categories/groups': Collection,
    'categories/settings': Sliders,
    // A grid, because that is literally the surface: rows down, options across.
    'categories/subcategories': Grid3x3,
    'levels/list': Layers,
    'levels/settings': Sliders,
    'levels/subcategories': Grid3x3,
    boards: Trophy,
    moderators: ShieldLock,
    reassign: ArrowLeftRight,
    import: CloudDownload,
    'match-runners': PersonCheck,
};
